SRCS=\
     ContactInfoTag.cpp \
     ContactInfoTagLoaderDatabase.cpp \
     ContactInfoTagLoaderFactory.cpp \
 
LIB=contacttags.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
