SRCS=\
     PictureInfoTag.cpp \
     PictureInfoTagLoaderJPG.cpp \
     PictureInfoTagLoaderDatabase.cpp \
     PictureInfoTagLoaderFactory.cpp \
 
LIB=picturetags.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
