SRCS=PictureAlbumInfo.cpp \
     PictureFaceInfo.cpp \
     PictureInfoScanner.cpp \
     PictureInfoScraper.cpp \

LIB=picturescanner.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
