SRCS=DirectoryNode.cpp \
     DirectoryNodeRoot.cpp \
     DirectoryNodeContact.cpp \
     DirectoryNodeFace.cpp \
     DirectoryNodeContactRecentlyAdded.cpp \
     DirectoryNodeOverview.cpp \
     QueryParams.cpp \


LIB=contactdatabasedirectory.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
